email: cristiadu@gmail.com
url: "https://blog.cristianofaustino.me"
markdown: kramdown
twitter_username: cristiadu
github_username:  cristiadu
theme: jekyll-theme-console
baseurl: ""
plugins:
  - jekyll-seo-tag
title: Cristiano's Box
email: cristiadu@gmail.com
description:  My hub of multiple blogs of the most varied subjects.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom folders to be ignored.
  - blogs/ # Ignore subblogs as they have their own build.

header_pages:
  - index.md
  - about.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: dark # dark (default) or light

# Custom fields
blog: home

