url: "https://blog.cristianofaustino.me"
baseurl: ""
title: Cristiano's Box
author: Cristiano Faustino
email: cristiadu@gmail.com
description: My hub of multiple blogs of the most varied subjects.
blog: home

# Theme Settings
remote_theme: abhinavs/moonwalk

# Social
github_username: cristiadu

# Plugins
plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - blogs/ # Ignore subblogs as they have their own build
sass:
  style: compressed

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_old_projects: false
  show_misc_list: true
  show_reading_time: true
  show_tags: true
  home:
    title_projects: Blogs
    title_misc_list: About Me
    title_blog: Posts
    title_old_projects: Other Links
