# Doltremare Blog: Jekyll Configuration

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
minimal_mistakes_skin: "sunrise"

# Site Settings
locale: "en-US"
description: "My creative writing endeavors."
url: "https://blog.cristianofaustino.me"
baseurl: "/doltremare"
repository: "cristiadu/blog"
logo: "/assets/images/doltremare-logo.png"
words_per_minute: 200
date_format: "%B %-d, %Y"
search: true

# Site Author
author:
  name: "Cristiano Faustino"
  avatar: "/assets/images/cristiano-profile.jpeg"
  bio: "Writes code most of the time, sometimes writes other words."
  location: "British Columbia, Canada"
  email: "cristiadu@gmail.com"
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://cristianofaustino.me"
    - label: "Blog"
      icon: "fas fa-fw fa-book"
      url: "https://blog.cristianofaustino.me"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cristianofaustino/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cristiadu"
    - label: "Last.fm"
      icon: "fab fa-fw fa-lastfm"
      url: "https://www.last.fm/user/cristiadu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/cristiadu"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cristiadu@gmail.com"
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://cristianofaustino.me"
    - label: "Blog"
      icon: "fas fa-fw fa-book"
      url: "https://blog.cristianofaustino.me"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cristianofaustino/"
    - label: "Last.fm"
      icon: "fab fa-fw fa-lastfm"
      url: "https://www.last.fm/user/cristiadu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cristiadu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/cristiadu7777"

# Reading Files
include:
  - _pages
exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

# Sass/SCSS
sass:
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true

      share: true
      related: true
