# Coding Blog Configuration
url: "https://blog.cristianofaustino.me"
baseurl: "/coding"
title: Cristiano's Box
email: cristiadu@gmail.com
description: My blog about coding.
blog: coding

# Theme Settings
theme: jekyll-theme-console
style: dark

# Social
github_username: cristiadu

# Navigation
header_pages:
  - index.md
  - about.md

footer: 'Made by <a href="https://cristianofaustino.me/">Cristiano Faustino</a>'

# Plugins
plugins:
  - jekyll-seo-tag
