# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Defining collections to represent each sub-blog.
email: cristiadu@gmail.com
url: "https://blog.cristianofaustino.me"
markdown: kramdown
twitter_username: cristiadu
github_username:  cristiadu
theme: jekyll-theme-console
baseurl: "/coding"
plugins:
  - jekyll-seo-tag
title: Cristiano's Box
email: cristiadu@gmail.com
description:  My hub of multiple blogs of the most varied subjects.

header_pages:
  - index.md
  - about.md

footer: 'Made by <a href="https://cristianofaustino.me/">Cristiano Faustino</a>'

style: dark # dark (default) or light

# Custom fields
blog: coding