# Inherit shared dependencies
eval_gemfile "../../Gemfile.base"

# Blog-specific dependencies
group :jekyll_plugins do
  gem 'jekyll-seo-tag', '~> 2.8.0'
end

# Custom added theme
gem "jekyll-theme-console"